// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod ironmesh {

    #[allow(unused_imports, dead_code)]
    pub mod protocol {

        #[allow(unused_imports, dead_code)]
        pub mod cluster {

            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MIN_IRON_CLUSTER_NODE_ROLE: u8 = 0;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MAX_IRON_CLUSTER_NODE_ROLE: u8 = 2;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            #[allow(non_camel_case_types)]
            pub const ENUM_VALUES_IRON_CLUSTER_NODE_ROLE: [IronClusterNodeRole; 3] = [
                IronClusterNodeRole::Gateway,
                IronClusterNodeRole::Business,
                IronClusterNodeRole::Control,
            ];

            #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
            #[repr(transparent)]
            pub struct IronClusterNodeRole(pub u8);
            #[allow(non_upper_case_globals)]
            impl IronClusterNodeRole {
                pub const Gateway: Self = Self(0);
                pub const Business: Self = Self(1);
                pub const Control: Self = Self(2);

                pub const ENUM_MIN: u8 = 0;
                pub const ENUM_MAX: u8 = 2;
                pub const ENUM_VALUES: &'static [Self] =
                    &[Self::Gateway, Self::Business, Self::Control];
                /// Returns the variant's name or "" if unknown.
                pub fn variant_name(self) -> Option<&'static str> {
                    match self {
                        Self::Gateway => Some("Gateway"),
                        Self::Business => Some("Business"),
                        Self::Control => Some("Control"),
                        _ => None,
                    }
                }
            }
            impl ::core::fmt::Debug for IronClusterNodeRole {
                fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                    if let Some(name) = self.variant_name() {
                        f.write_str(name)
                    } else {
                        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                    }
                }
            }
            impl<'a> ::flatbuffers::Follow<'a> for IronClusterNodeRole {
                type Inner = Self;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                    Self(b)
                }
            }

            impl ::flatbuffers::Push for IronClusterNodeRole {
                type Output = IronClusterNodeRole;
                #[inline]
                unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                    unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
                }
            }

            impl ::flatbuffers::EndianScalar for IronClusterNodeRole {
                type Scalar = u8;
                #[inline]
                fn to_little_endian(self) -> u8 {
                    self.0.to_le()
                }
                #[inline]
                #[allow(clippy::wrong_self_convention)]
                fn from_little_endian(v: u8) -> Self {
                    let b = u8::from_le(v);
                    Self(b)
                }
            }

            impl<'a> ::flatbuffers::Verifiable for IronClusterNodeRole {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    u8::run_verifier(v, pos)
                }
            }

            impl ::flatbuffers::SimpleToVerifyInSlice for IronClusterNodeRole {}
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MIN_IRON_CLUSTER_STATE: u8 = 0;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MAX_IRON_CLUSTER_STATE: u8 = 3;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            #[allow(non_camel_case_types)]
            pub const ENUM_VALUES_IRON_CLUSTER_STATE: [IronClusterState; 4] = [
                IronClusterState::Unknown,
                IronClusterState::Starting,
                IronClusterState::Healthy,
                IronClusterState::Offline,
            ];

            #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
            #[repr(transparent)]
            pub struct IronClusterState(pub u8);
            #[allow(non_upper_case_globals)]
            impl IronClusterState {
                pub const Unknown: Self = Self(0);
                pub const Starting: Self = Self(1);
                pub const Healthy: Self = Self(2);
                pub const Offline: Self = Self(3);

                pub const ENUM_MIN: u8 = 0;
                pub const ENUM_MAX: u8 = 3;
                pub const ENUM_VALUES: &'static [Self] =
                    &[Self::Unknown, Self::Starting, Self::Healthy, Self::Offline];
                /// Returns the variant's name or "" if unknown.
                pub fn variant_name(self) -> Option<&'static str> {
                    match self {
                        Self::Unknown => Some("Unknown"),
                        Self::Starting => Some("Starting"),
                        Self::Healthy => Some("Healthy"),
                        Self::Offline => Some("Offline"),
                        _ => None,
                    }
                }
            }
            impl ::core::fmt::Debug for IronClusterState {
                fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                    if let Some(name) = self.variant_name() {
                        f.write_str(name)
                    } else {
                        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                    }
                }
            }
            impl<'a> ::flatbuffers::Follow<'a> for IronClusterState {
                type Inner = Self;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                    Self(b)
                }
            }

            impl ::flatbuffers::Push for IronClusterState {
                type Output = IronClusterState;
                #[inline]
                unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                    unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
                }
            }

            impl ::flatbuffers::EndianScalar for IronClusterState {
                type Scalar = u8;
                #[inline]
                fn to_little_endian(self) -> u8 {
                    self.0.to_le()
                }
                #[inline]
                #[allow(clippy::wrong_self_convention)]
                fn from_little_endian(v: u8) -> Self {
                    let b = u8::from_le(v);
                    Self(b)
                }
            }

            impl<'a> ::flatbuffers::Verifiable for IronClusterState {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    u8::run_verifier(v, pos)
                }
            }

            impl ::flatbuffers::SimpleToVerifyInSlice for IronClusterState {}
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MIN_IRON_CLUSTER_ENDPOINT_PROTOCOL: u8 = 0;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            pub const ENUM_MAX_IRON_CLUSTER_ENDPOINT_PROTOCOL: u8 = 1;
            #[deprecated(
                since = "2.0.0",
                note = "Use associated constants instead. This will no longer be generated in 2021."
            )]
            #[allow(non_camel_case_types)]
            pub const ENUM_VALUES_IRON_CLUSTER_ENDPOINT_PROTOCOL: [IronClusterEndpointProtocol; 2] = [
                IronClusterEndpointProtocol::Tcp,
                IronClusterEndpointProtocol::Http,
            ];

            #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
            #[repr(transparent)]
            pub struct IronClusterEndpointProtocol(pub u8);
            #[allow(non_upper_case_globals)]
            impl IronClusterEndpointProtocol {
                pub const Tcp: Self = Self(0);
                pub const Http: Self = Self(1);

                pub const ENUM_MIN: u8 = 0;
                pub const ENUM_MAX: u8 = 1;
                pub const ENUM_VALUES: &'static [Self] = &[Self::Tcp, Self::Http];
                /// Returns the variant's name or "" if unknown.
                pub fn variant_name(self) -> Option<&'static str> {
                    match self {
                        Self::Tcp => Some("Tcp"),
                        Self::Http => Some("Http"),
                        _ => None,
                    }
                }
            }
            impl ::core::fmt::Debug for IronClusterEndpointProtocol {
                fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                    if let Some(name) = self.variant_name() {
                        f.write_str(name)
                    } else {
                        f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                    }
                }
            }
            impl<'a> ::flatbuffers::Follow<'a> for IronClusterEndpointProtocol {
                type Inner = Self;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                    Self(b)
                }
            }

            impl ::flatbuffers::Push for IronClusterEndpointProtocol {
                type Output = IronClusterEndpointProtocol;
                #[inline]
                unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                    unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
                }
            }

            impl ::flatbuffers::EndianScalar for IronClusterEndpointProtocol {
                type Scalar = u8;
                #[inline]
                fn to_little_endian(self) -> u8 {
                    self.0.to_le()
                }
                #[inline]
                #[allow(clippy::wrong_self_convention)]
                fn from_little_endian(v: u8) -> Self {
                    let b = u8::from_le(v);
                    Self(b)
                }
            }

            impl<'a> ::flatbuffers::Verifiable for IronClusterEndpointProtocol {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    u8::run_verifier(v, pos)
                }
            }

            impl ::flatbuffers::SimpleToVerifyInSlice for IronClusterEndpointProtocol {}
            pub enum IronClusterEndpointOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct IronClusterEndpoint<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for IronClusterEndpoint<'a> {
                type Inner = IronClusterEndpoint<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> IronClusterEndpoint<'a> {
                pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
                pub const VT_PROTOCOL: ::flatbuffers::VOffsetT = 6;
                pub const VT_HOST: ::flatbuffers::VOffsetT = 8;
                pub const VT_PORT: ::flatbuffers::VOffsetT = 10;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    IronClusterEndpoint { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args IronClusterEndpointArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<IronClusterEndpoint<'bldr>> {
                    let mut builder = IronClusterEndpointBuilder::new(_fbb);
                    if let Some(x) = args.host {
                        builder.add_host(x);
                    }
                    if let Some(x) = args.name {
                        builder.add_name(x);
                    }
                    builder.add_port(args.port);
                    builder.add_protocol(args.protocol);
                    builder.finish()
                }

                #[inline]
                pub fn name(&self) -> Option<&'a str> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                            IronClusterEndpoint::VT_NAME,
                            None,
                        )
                    }
                }
                #[inline]
                pub fn protocol(&self) -> IronClusterEndpointProtocol {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<IronClusterEndpointProtocol>(
                                IronClusterEndpoint::VT_PROTOCOL,
                                Some(IronClusterEndpointProtocol::Tcp),
                            )
                            .unwrap()
                    }
                }
                #[inline]
                pub fn host(&self) -> Option<&'a str> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                            IronClusterEndpoint::VT_HOST,
                            None,
                        )
                    }
                }
                #[inline]
                pub fn port(&self) -> u16 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<u16>(IronClusterEndpoint::VT_PORT, Some(0))
                            .unwrap()
                    }
                }
            }

            impl ::flatbuffers::Verifiable for IronClusterEndpoint<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                            "name",
                            Self::VT_NAME,
                            false,
                        )?
                        .visit_field::<IronClusterEndpointProtocol>(
                            "protocol",
                            Self::VT_PROTOCOL,
                            false,
                        )?
                        .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                            "host",
                            Self::VT_HOST,
                            false,
                        )?
                        .visit_field::<u16>("port", Self::VT_PORT, false)?
                        .finish();
                    Ok(())
                }
            }
            pub struct IronClusterEndpointArgs<'a> {
                pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
                pub protocol: IronClusterEndpointProtocol,
                pub host: Option<::flatbuffers::WIPOffset<&'a str>>,
                pub port: u16,
            }
            impl<'a> Default for IronClusterEndpointArgs<'a> {
                #[inline]
                fn default() -> Self {
                    IronClusterEndpointArgs {
                        name: None,
                        protocol: IronClusterEndpointProtocol::Tcp,
                        host: None,
                        port: 0,
                    }
                }
            }

            pub struct IronClusterEndpointBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterEndpointBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b str>) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterEndpoint::VT_NAME,
                        name,
                    );
                }
                #[inline]
                pub fn add_protocol(&mut self, protocol: IronClusterEndpointProtocol) {
                    self.fbb_.push_slot::<IronClusterEndpointProtocol>(
                        IronClusterEndpoint::VT_PROTOCOL,
                        protocol,
                        IronClusterEndpointProtocol::Tcp,
                    );
                }
                #[inline]
                pub fn add_host(&mut self, host: ::flatbuffers::WIPOffset<&'b str>) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterEndpoint::VT_HOST,
                        host,
                    );
                }
                #[inline]
                pub fn add_port(&mut self, port: u16) {
                    self.fbb_
                        .push_slot::<u16>(IronClusterEndpoint::VT_PORT, port, 0);
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> IronClusterEndpointBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    IronClusterEndpointBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterEndpoint<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for IronClusterEndpoint<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("IronClusterEndpoint");
                    ds.field("name", &self.name());
                    ds.field("protocol", &self.protocol());
                    ds.field("host", &self.host());
                    ds.field("port", &self.port());
                    ds.finish()
                }
            }
            pub enum IronClusterServiceOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct IronClusterService<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for IronClusterService<'a> {
                type Inner = IronClusterService<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> IronClusterService<'a> {
                pub const VT_SERVICE_NAME: ::flatbuffers::VOffsetT = 4;
                pub const VT_STATE: ::flatbuffers::VOffsetT = 6;
                pub const VT_ENDPOINTS: ::flatbuffers::VOffsetT = 8;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    IronClusterService { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args IronClusterServiceArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<IronClusterService<'bldr>> {
                    let mut builder = IronClusterServiceBuilder::new(_fbb);
                    if let Some(x) = args.endpoints {
                        builder.add_endpoints(x);
                    }
                    if let Some(x) = args.service_name {
                        builder.add_service_name(x);
                    }
                    builder.add_state(args.state);
                    builder.finish()
                }

                #[inline]
                pub fn service_name(&self) -> Option<&'a str> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                            IronClusterService::VT_SERVICE_NAME,
                            None,
                        )
                    }
                }
                #[inline]
                pub fn state(&self) -> IronClusterState {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<IronClusterState>(
                                IronClusterService::VT_STATE,
                                Some(IronClusterState::Unknown),
                            )
                            .unwrap()
                    }
                }
                #[inline]
                pub fn endpoints(
                    &self,
                ) -> Option<
                    ::flatbuffers::Vector<
                        'a,
                        ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'a>>,
                    >,
                > {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                'a,
                                ::flatbuffers::ForwardsUOffset<IronClusterEndpoint>,
                            >,
                        >>(IronClusterService::VT_ENDPOINTS, None)
                    }
                }
            }

            impl ::flatbuffers::Verifiable for IronClusterService<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                            "service_name",
                            Self::VT_SERVICE_NAME,
                            false,
                        )?
                        .visit_field::<IronClusterState>("state", Self::VT_STATE, false)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                '_,
                                ::flatbuffers::ForwardsUOffset<IronClusterEndpoint>,
                            >,
                        >>("endpoints", Self::VT_ENDPOINTS, false)?
                        .finish();
                    Ok(())
                }
            }
            pub struct IronClusterServiceArgs<'a> {
                pub service_name: Option<::flatbuffers::WIPOffset<&'a str>>,
                pub state: IronClusterState,
                pub endpoints: Option<
                    ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'a,
                            ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'a>>,
                        >,
                    >,
                >,
            }
            impl<'a> Default for IronClusterServiceArgs<'a> {
                #[inline]
                fn default() -> Self {
                    IronClusterServiceArgs {
                        service_name: None,
                        state: IronClusterState::Unknown,
                        endpoints: None,
                    }
                }
            }

            pub struct IronClusterServiceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterServiceBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_service_name(
                    &mut self,
                    service_name: ::flatbuffers::WIPOffset<&'b str>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterService::VT_SERVICE_NAME,
                        service_name,
                    );
                }
                #[inline]
                pub fn add_state(&mut self, state: IronClusterState) {
                    self.fbb_.push_slot::<IronClusterState>(
                        IronClusterService::VT_STATE,
                        state,
                        IronClusterState::Unknown,
                    );
                }
                #[inline]
                pub fn add_endpoints(
                    &mut self,
                    endpoints: ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'b,
                            ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'b>>,
                        >,
                    >,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterService::VT_ENDPOINTS,
                        endpoints,
                    );
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> IronClusterServiceBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    IronClusterServiceBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterService<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for IronClusterService<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("IronClusterService");
                    ds.field("service_name", &self.service_name());
                    ds.field("state", &self.state());
                    ds.field("endpoints", &self.endpoints());
                    ds.finish()
                }
            }
            pub enum IronClusterNodeOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct IronClusterNode<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for IronClusterNode<'a> {
                type Inner = IronClusterNode<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> IronClusterNode<'a> {
                pub const VT_NODE_ID: ::flatbuffers::VOffsetT = 4;
                pub const VT_ROLE: ::flatbuffers::VOffsetT = 6;
                pub const VT_STATE: ::flatbuffers::VOffsetT = 8;
                pub const VT_SERVICES: ::flatbuffers::VOffsetT = 10;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    IronClusterNode { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args IronClusterNodeArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<IronClusterNode<'bldr>> {
                    let mut builder = IronClusterNodeBuilder::new(_fbb);
                    if let Some(x) = args.services {
                        builder.add_services(x);
                    }
                    if let Some(x) = args.node_id {
                        builder.add_node_id(x);
                    }
                    builder.add_state(args.state);
                    builder.add_role(args.role);
                    builder.finish()
                }

                #[inline]
                pub fn node_id(&self) -> Option<&'a str> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                            IronClusterNode::VT_NODE_ID,
                            None,
                        )
                    }
                }
                #[inline]
                pub fn role(&self) -> IronClusterNodeRole {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<IronClusterNodeRole>(
                                IronClusterNode::VT_ROLE,
                                Some(IronClusterNodeRole::Gateway),
                            )
                            .unwrap()
                    }
                }
                #[inline]
                pub fn state(&self) -> IronClusterState {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<IronClusterState>(
                                IronClusterNode::VT_STATE,
                                Some(IronClusterState::Unknown),
                            )
                            .unwrap()
                    }
                }
                #[inline]
                pub fn services(
                    &self,
                ) -> Option<
                    ::flatbuffers::Vector<
                        'a,
                        ::flatbuffers::ForwardsUOffset<IronClusterService<'a>>,
                    >,
                > {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                'a,
                                ::flatbuffers::ForwardsUOffset<IronClusterService>,
                            >,
                        >>(IronClusterNode::VT_SERVICES, None)
                    }
                }
            }

            impl ::flatbuffers::Verifiable for IronClusterNode<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                            "node_id",
                            Self::VT_NODE_ID,
                            false,
                        )?
                        .visit_field::<IronClusterNodeRole>("role", Self::VT_ROLE, false)?
                        .visit_field::<IronClusterState>("state", Self::VT_STATE, false)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                '_,
                                ::flatbuffers::ForwardsUOffset<IronClusterService>,
                            >,
                        >>("services", Self::VT_SERVICES, false)?
                        .finish();
                    Ok(())
                }
            }
            pub struct IronClusterNodeArgs<'a> {
                pub node_id: Option<::flatbuffers::WIPOffset<&'a str>>,
                pub role: IronClusterNodeRole,
                pub state: IronClusterState,
                pub services: Option<
                    ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'a,
                            ::flatbuffers::ForwardsUOffset<IronClusterService<'a>>,
                        >,
                    >,
                >,
            }
            impl<'a> Default for IronClusterNodeArgs<'a> {
                #[inline]
                fn default() -> Self {
                    IronClusterNodeArgs {
                        node_id: None,
                        role: IronClusterNodeRole::Gateway,
                        state: IronClusterState::Unknown,
                        services: None,
                    }
                }
            }

            pub struct IronClusterNodeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterNodeBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_node_id(&mut self, node_id: ::flatbuffers::WIPOffset<&'b str>) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterNode::VT_NODE_ID,
                        node_id,
                    );
                }
                #[inline]
                pub fn add_role(&mut self, role: IronClusterNodeRole) {
                    self.fbb_.push_slot::<IronClusterNodeRole>(
                        IronClusterNode::VT_ROLE,
                        role,
                        IronClusterNodeRole::Gateway,
                    );
                }
                #[inline]
                pub fn add_state(&mut self, state: IronClusterState) {
                    self.fbb_.push_slot::<IronClusterState>(
                        IronClusterNode::VT_STATE,
                        state,
                        IronClusterState::Unknown,
                    );
                }
                #[inline]
                pub fn add_services(
                    &mut self,
                    services: ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'b,
                            ::flatbuffers::ForwardsUOffset<IronClusterService<'b>>,
                        >,
                    >,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterNode::VT_SERVICES,
                        services,
                    );
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> IronClusterNodeBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    IronClusterNodeBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterNode<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for IronClusterNode<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("IronClusterNode");
                    ds.field("node_id", &self.node_id());
                    ds.field("role", &self.role());
                    ds.field("state", &self.state());
                    ds.field("services", &self.services());
                    ds.finish()
                }
            }
            pub enum IronClusterSnapOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct IronClusterSnap<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for IronClusterSnap<'a> {
                type Inner = IronClusterSnap<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> IronClusterSnap<'a> {
                pub const VT_CLUSTER_ID: ::flatbuffers::VOffsetT = 4;
                pub const VT_METADATA_VERSION: ::flatbuffers::VOffsetT = 6;
                pub const VT_NODES: ::flatbuffers::VOffsetT = 8;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    IronClusterSnap { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args IronClusterSnapArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<IronClusterSnap<'bldr>> {
                    let mut builder = IronClusterSnapBuilder::new(_fbb);
                    builder.add_metadata_version(args.metadata_version);
                    if let Some(x) = args.nodes {
                        builder.add_nodes(x);
                    }
                    if let Some(x) = args.cluster_id {
                        builder.add_cluster_id(x);
                    }
                    builder.finish()
                }

                #[inline]
                pub fn cluster_id(&self) -> Option<&'a str> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                            IronClusterSnap::VT_CLUSTER_ID,
                            None,
                        )
                    }
                }
                #[inline]
                pub fn metadata_version(&self) -> u64 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<u64>(IronClusterSnap::VT_METADATA_VERSION, Some(0))
                            .unwrap()
                    }
                }
                #[inline]
                pub fn nodes(
                    &self,
                ) -> Option<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterNode<'a>>>,
                > {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab.get::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                'a,
                                ::flatbuffers::ForwardsUOffset<IronClusterNode>,
                            >,
                        >>(IronClusterSnap::VT_NODES, None)
                    }
                }
            }

            impl ::flatbuffers::Verifiable for IronClusterSnap<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                            "cluster_id",
                            Self::VT_CLUSTER_ID,
                            false,
                        )?
                        .visit_field::<u64>("metadata_version", Self::VT_METADATA_VERSION, false)?
                        .visit_field::<::flatbuffers::ForwardsUOffset<
                            ::flatbuffers::Vector<
                                '_,
                                ::flatbuffers::ForwardsUOffset<IronClusterNode>,
                            >,
                        >>("nodes", Self::VT_NODES, false)?
                        .finish();
                    Ok(())
                }
            }
            pub struct IronClusterSnapArgs<'a> {
                pub cluster_id: Option<::flatbuffers::WIPOffset<&'a str>>,
                pub metadata_version: u64,
                pub nodes: Option<
                    ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'a,
                            ::flatbuffers::ForwardsUOffset<IronClusterNode<'a>>,
                        >,
                    >,
                >,
            }
            impl<'a> Default for IronClusterSnapArgs<'a> {
                #[inline]
                fn default() -> Self {
                    IronClusterSnapArgs {
                        cluster_id: None,
                        metadata_version: 0,
                        nodes: None,
                    }
                }
            }

            pub struct IronClusterSnapBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterSnapBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_cluster_id(&mut self, cluster_id: ::flatbuffers::WIPOffset<&'b str>) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterSnap::VT_CLUSTER_ID,
                        cluster_id,
                    );
                }
                #[inline]
                pub fn add_metadata_version(&mut self, metadata_version: u64) {
                    self.fbb_.push_slot::<u64>(
                        IronClusterSnap::VT_METADATA_VERSION,
                        metadata_version,
                        0,
                    );
                }
                #[inline]
                pub fn add_nodes(
                    &mut self,
                    nodes: ::flatbuffers::WIPOffset<
                        ::flatbuffers::Vector<
                            'b,
                            ::flatbuffers::ForwardsUOffset<IronClusterNode<'b>>,
                        >,
                    >,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        IronClusterSnap::VT_NODES,
                        nodes,
                    );
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> IronClusterSnapBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    IronClusterSnapBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterSnap<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for IronClusterSnap<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("IronClusterSnap");
                    ds.field("cluster_id", &self.cluster_id());
                    ds.field("metadata_version", &self.metadata_version());
                    ds.field("nodes", &self.nodes());
                    ds.finish()
                }
            }
            #[inline]
            /// Verifies that a buffer of bytes contains a `IronClusterSnap`
            /// and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_iron_cluster_snap_unchecked`.
            pub fn root_as_iron_cluster_snap(
                buf: &[u8],
            ) -> Result<IronClusterSnap<'_>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::root::<IronClusterSnap>(buf)
            }
            #[inline]
            /// Verifies that a buffer of bytes contains a size prefixed
            /// `IronClusterSnap` and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `size_prefixed_root_as_iron_cluster_snap_unchecked`.
            pub fn size_prefixed_root_as_iron_cluster_snap(
                buf: &[u8],
            ) -> Result<IronClusterSnap<'_>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::size_prefixed_root::<IronClusterSnap>(buf)
            }
            #[inline]
            /// Verifies, with the given options, that a buffer of bytes
            /// contains a `IronClusterSnap` and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_iron_cluster_snap_unchecked`.
            pub fn root_as_iron_cluster_snap_with_opts<'b, 'o>(
                opts: &'o ::flatbuffers::VerifierOptions,
                buf: &'b [u8],
            ) -> Result<IronClusterSnap<'b>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::root_with_opts::<IronClusterSnap<'b>>(opts, buf)
            }
            #[inline]
            /// Verifies, with the given verifier options, that a buffer of
            /// bytes contains a size prefixed `IronClusterSnap` and returns
            /// it. Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_iron_cluster_snap_unchecked`.
            pub fn size_prefixed_root_as_iron_cluster_snap_with_opts<'b, 'o>(
                opts: &'o ::flatbuffers::VerifierOptions,
                buf: &'b [u8],
            ) -> Result<IronClusterSnap<'b>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::size_prefixed_root_with_opts::<IronClusterSnap<'b>>(opts, buf)
            }
            #[inline]
            /// Assumes, without verification, that a buffer of bytes contains a IronClusterSnap and returns it.
            /// # Safety
            /// Callers must trust the given bytes do indeed contain a valid `IronClusterSnap`.
            pub unsafe fn root_as_iron_cluster_snap_unchecked(buf: &[u8]) -> IronClusterSnap<'_> {
                unsafe { ::flatbuffers::root_unchecked::<IronClusterSnap>(buf) }
            }
            #[inline]
            /// Assumes, without verification, that a buffer of bytes contains a size prefixed IronClusterSnap and returns it.
            /// # Safety
            /// Callers must trust the given bytes do indeed contain a valid size prefixed `IronClusterSnap`.
            pub unsafe fn size_prefixed_root_as_iron_cluster_snap_unchecked(
                buf: &[u8],
            ) -> IronClusterSnap<'_> {
                unsafe { ::flatbuffers::size_prefixed_root_unchecked::<IronClusterSnap>(buf) }
            }
            #[inline]
            pub fn finish_iron_cluster_snap_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
                fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                root: ::flatbuffers::WIPOffset<IronClusterSnap<'a>>,
            ) {
                fbb.finish(root, None);
            }

            #[inline]
            pub fn finish_size_prefixed_iron_cluster_snap_buffer<
                'a,
                'b,
                A: ::flatbuffers::Allocator + 'a,
            >(
                fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                root: ::flatbuffers::WIPOffset<IronClusterSnap<'a>>,
            ) {
                fbb.finish_size_prefixed(root, None);
            }
        } // pub mod cluster
    } // pub mod protocol
} // pub mod ironmesh
