// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronAuthLoginReqOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronAuthLoginReq<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronAuthLoginReq<'a> {
    type Inner = IronAuthLoginReq<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronAuthLoginReq<'a> {
    pub const VT_ACCOUNT: ::flatbuffers::VOffsetT = 4;
    pub const VT_PASSWORD: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronAuthLoginReq { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronAuthLoginReqArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronAuthLoginReq<'bldr>> {
        let mut builder = IronAuthLoginReqBuilder::new(_fbb);
        if let Some(x) = args.password {
            builder.add_password(x);
        }
        if let Some(x) = args.account {
            builder.add_account(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn account(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronAuthLoginReq::VT_ACCOUNT, None)
        }
    }
    #[inline]
    pub fn password(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronAuthLoginReq::VT_PASSWORD, None)
        }
    }
}

impl ::flatbuffers::Verifiable for IronAuthLoginReq<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                "account",
                Self::VT_ACCOUNT,
                false,
            )?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                "password",
                Self::VT_PASSWORD,
                false,
            )?
            .finish();
        Ok(())
    }
}
pub struct IronAuthLoginReqArgs<'a> {
    pub account: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub password: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for IronAuthLoginReqArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronAuthLoginReqArgs {
            account: None,
            password: None,
        }
    }
}

pub struct IronAuthLoginReqBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronAuthLoginReqBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_account(&mut self, account: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronAuthLoginReq::VT_ACCOUNT, account);
    }
    #[inline]
    pub fn add_password(&mut self, password: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            IronAuthLoginReq::VT_PASSWORD,
            password,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronAuthLoginReqBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronAuthLoginReqBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronAuthLoginReq<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronAuthLoginReq<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronAuthLoginReq");
        ds.field("account", &self.account());
        ds.field("password", &self.password());
        ds.finish()
    }
}
