// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronAuthRegisterRespOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronAuthRegisterResp<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronAuthRegisterResp<'a> {
    type Inner = IronAuthRegisterResp<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronAuthRegisterResp<'a> {
    pub const VT_CODE: ::flatbuffers::VOffsetT = 4;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronAuthRegisterResp { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronAuthRegisterRespArgs,
    ) -> ::flatbuffers::WIPOffset<IronAuthRegisterResp<'bldr>> {
        let mut builder = IronAuthRegisterRespBuilder::new(_fbb);
        builder.add_code(args.code);
        builder.finish()
    }

    #[inline]
    pub fn code(&self) -> IronAuthErrorCode {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronAuthErrorCode>(
                    IronAuthRegisterResp::VT_CODE,
                    Some(IronAuthErrorCode::Ok),
                )
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IronAuthRegisterResp<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<IronAuthErrorCode>("code", Self::VT_CODE, false)?
            .finish();
        Ok(())
    }
}
pub struct IronAuthRegisterRespArgs {
    pub code: IronAuthErrorCode,
}
impl<'a> Default for IronAuthRegisterRespArgs {
    #[inline]
    fn default() -> Self {
        IronAuthRegisterRespArgs {
            code: IronAuthErrorCode::Ok,
        }
    }
}

pub struct IronAuthRegisterRespBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronAuthRegisterRespBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_code(&mut self, code: IronAuthErrorCode) {
        self.fbb_.push_slot::<IronAuthErrorCode>(
            IronAuthRegisterResp::VT_CODE,
            code,
            IronAuthErrorCode::Ok,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronAuthRegisterRespBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronAuthRegisterRespBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronAuthRegisterResp<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronAuthRegisterResp<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronAuthRegisterResp");
        ds.field("code", &self.code());
        ds.finish()
    }
}
