// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_IRON_AUTH_PAYLOAD: u8 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_IRON_AUTH_PAYLOAD: u8 = 4;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_IRON_AUTH_PAYLOAD: [IronAuthPayload; 5] = [
    IronAuthPayload::NONE,
    IronAuthPayload::IronAuthLoginReq,
    IronAuthPayload::IronAuthLoginResp,
    IronAuthPayload::IronAuthRegisterReq,
    IronAuthPayload::IronAuthRegisterResp,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IronAuthPayload(pub u8);
#[allow(non_upper_case_globals)]
impl IronAuthPayload {
    pub const NONE: Self = Self(0);
    pub const IronAuthLoginReq: Self = Self(1);
    pub const IronAuthLoginResp: Self = Self(2);
    pub const IronAuthRegisterReq: Self = Self(3);
    pub const IronAuthRegisterResp: Self = Self(4);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 4;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::NONE,
        Self::IronAuthLoginReq,
        Self::IronAuthLoginResp,
        Self::IronAuthRegisterReq,
        Self::IronAuthRegisterResp,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::NONE => Some("NONE"),
            Self::IronAuthLoginReq => Some("IronAuthLoginReq"),
            Self::IronAuthLoginResp => Some("IronAuthLoginResp"),
            Self::IronAuthRegisterReq => Some("IronAuthRegisterReq"),
            Self::IronAuthRegisterResp => Some("IronAuthRegisterResp"),
            _ => None,
        }
    }
}
impl ::core::fmt::Debug for IronAuthPayload {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> ::flatbuffers::Follow<'a> for IronAuthPayload {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
        Self(b)
    }
}

impl ::flatbuffers::Push for IronAuthPayload {
    type Output = IronAuthPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for IronAuthPayload {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: u8) -> Self {
        let b = u8::from_le(v);
        Self(b)
    }
}

impl<'a> ::flatbuffers::Verifiable for IronAuthPayload {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        u8::run_verifier(v, pos)
    }
}

impl ::flatbuffers::SimpleToVerifyInSlice for IronAuthPayload {}
pub struct IronAuthPayloadUnionTableOffset {}
