// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronAuthMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronAuthMessage<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronAuthMessage<'a> {
    type Inner = IronAuthMessage<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronAuthMessage<'a> {
    pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
    pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronAuthMessage { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronAuthMessageArgs,
    ) -> ::flatbuffers::WIPOffset<IronAuthMessage<'bldr>> {
        let mut builder = IronAuthMessageBuilder::new(_fbb);
        if let Some(x) = args.payload {
            builder.add_payload(x);
        }
        builder.add_payload_type(args.payload_type);
        builder.finish()
    }

    #[inline]
    pub fn payload_type(&self) -> IronAuthPayload {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronAuthPayload>(
                    IronAuthMessage::VT_PAYLOAD_TYPE,
                    Some(IronAuthPayload::NONE),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    IronAuthMessage::VT_PAYLOAD,
                    None,
                )
        }
    }
    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_auth_login_req(&self) -> Option<IronAuthLoginReq<'a>> {
        if self.payload_type() == IronAuthPayload::IronAuthLoginReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronAuthLoginReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_auth_login_resp(&self) -> Option<IronAuthLoginResp<'a>> {
        if self.payload_type() == IronAuthPayload::IronAuthLoginResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronAuthLoginResp::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_auth_register_req(&self) -> Option<IronAuthRegisterReq<'a>> {
        if self.payload_type() == IronAuthPayload::IronAuthRegisterReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronAuthRegisterReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_auth_register_resp(&self) -> Option<IronAuthRegisterResp<'a>> {
        if self.payload_type() == IronAuthPayload::IronAuthRegisterResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronAuthRegisterResp::init_from_table(t) }
            })
        } else {
            None
        }
    }
}

impl ::flatbuffers::Verifiable for IronAuthMessage<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
     .visit_union::<IronAuthPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          IronAuthPayload::IronAuthLoginReq => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronAuthLoginReq>>("IronAuthPayload::IronAuthLoginReq", pos),
          IronAuthPayload::IronAuthLoginResp => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronAuthLoginResp>>("IronAuthPayload::IronAuthLoginResp", pos),
          IronAuthPayload::IronAuthRegisterReq => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronAuthRegisterReq>>("IronAuthPayload::IronAuthRegisterReq", pos),
          IronAuthPayload::IronAuthRegisterResp => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronAuthRegisterResp>>("IronAuthPayload::IronAuthRegisterResp", pos),
          _ => Ok(()),
        }
     })?
     .finish();
        Ok(())
    }
}
pub struct IronAuthMessageArgs {
    pub payload_type: IronAuthPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for IronAuthMessageArgs {
    #[inline]
    fn default() -> Self {
        IronAuthMessageArgs {
            payload_type: IronAuthPayload::NONE,
            payload: None,
        }
    }
}

pub struct IronAuthMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronAuthMessageBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_payload_type(&mut self, payload_type: IronAuthPayload) {
        self.fbb_.push_slot::<IronAuthPayload>(
            IronAuthMessage::VT_PAYLOAD_TYPE,
            payload_type,
            IronAuthPayload::NONE,
        );
    }
    #[inline]
    pub fn add_payload(
        &mut self,
        payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronAuthMessage::VT_PAYLOAD, payload);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronAuthMessageBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronAuthMessageBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronAuthMessage<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronAuthMessage<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronAuthMessage");
        ds.field("payload_type", &self.payload_type());
        match self.payload_type() {
            IronAuthPayload::IronAuthLoginReq => {
                if let Some(x) = self.payload_as_iron_auth_login_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronAuthPayload::IronAuthLoginResp => {
                if let Some(x) = self.payload_as_iron_auth_login_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronAuthPayload::IronAuthRegisterReq => {
                if let Some(x) = self.payload_as_iron_auth_register_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronAuthPayload::IronAuthRegisterResp => {
                if let Some(x) = self.payload_as_iron_auth_register_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            _ => {
                let x: Option<()> = None;
                ds.field("payload", &x)
            }
        };
        ds.finish()
    }
}
