// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_IRON_BUSINESS_SERVICE_PAYLOAD: u8 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_IRON_BUSINESS_SERVICE_PAYLOAD: u8 = 3;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_IRON_BUSINESS_SERVICE_PAYLOAD: [IronBusinessServicePayload; 4] = [
    IronBusinessServicePayload::NONE,
    IronBusinessServicePayload::auth_IronAuthMessage,
    IronBusinessServicePayload::ddz_IronDdzMessage,
    IronBusinessServicePayload::pdk_IronPdkMessage,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IronBusinessServicePayload(pub u8);
#[allow(non_upper_case_globals)]
impl IronBusinessServicePayload {
    pub const NONE: Self = Self(0);
    pub const auth_IronAuthMessage: Self = Self(1);
    pub const ddz_IronDdzMessage: Self = Self(2);
    pub const pdk_IronPdkMessage: Self = Self(3);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 3;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::NONE,
        Self::auth_IronAuthMessage,
        Self::ddz_IronDdzMessage,
        Self::pdk_IronPdkMessage,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::NONE => Some("NONE"),
            Self::auth_IronAuthMessage => Some("auth_IronAuthMessage"),
            Self::ddz_IronDdzMessage => Some("ddz_IronDdzMessage"),
            Self::pdk_IronPdkMessage => Some("pdk_IronPdkMessage"),
            _ => None,
        }
    }
}
impl ::core::fmt::Debug for IronBusinessServicePayload {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> ::flatbuffers::Follow<'a> for IronBusinessServicePayload {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
        Self(b)
    }
}

impl ::flatbuffers::Push for IronBusinessServicePayload {
    type Output = IronBusinessServicePayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for IronBusinessServicePayload {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: u8) -> Self {
        let b = u8::from_le(v);
        Self(b)
    }
}

impl<'a> ::flatbuffers::Verifiable for IronBusinessServicePayload {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        u8::run_verifier(v, pos)
    }
}

impl ::flatbuffers::SimpleToVerifyInSlice for IronBusinessServicePayload {}
pub struct IronBusinessServicePayloadUnionTableOffset {}
