// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronBusinessBodyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronBusinessBody<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronBusinessBody<'a> {
    type Inner = IronBusinessBody<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronBusinessBody<'a> {
    pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
    pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronBusinessBody { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronBusinessBodyArgs,
    ) -> ::flatbuffers::WIPOffset<IronBusinessBody<'bldr>> {
        let mut builder = IronBusinessBodyBuilder::new(_fbb);
        if let Some(x) = args.payload {
            builder.add_payload(x);
        }
        builder.add_payload_type(args.payload_type);
        builder.finish()
    }

    #[inline]
    pub fn payload_type(&self) -> IronBusinessServicePayload {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronBusinessServicePayload>(
                    IronBusinessBody::VT_PAYLOAD_TYPE,
                    Some(IronBusinessServicePayload::NONE),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    IronBusinessBody::VT_PAYLOAD,
                    None,
                )
        }
    }
    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_auth_iron_auth_message(&self) -> Option<auth::IronAuthMessage<'a>> {
        if self.payload_type() == IronBusinessServicePayload::auth_IronAuthMessage {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { auth::IronAuthMessage::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_ddz_iron_ddz_message(&self) -> Option<ddz::IronDdzMessage<'a>> {
        if self.payload_type() == IronBusinessServicePayload::ddz_IronDdzMessage {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { ddz::IronDdzMessage::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_pdk_iron_pdk_message(&self) -> Option<pdk::IronPdkMessage<'a>> {
        if self.payload_type() == IronBusinessServicePayload::pdk_IronPdkMessage {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { pdk::IronPdkMessage::init_from_table(t) }
            })
        } else {
            None
        }
    }
}

impl ::flatbuffers::Verifiable for IronBusinessBody<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
     .visit_union::<IronBusinessServicePayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          IronBusinessServicePayload::auth_IronAuthMessage => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<auth::IronAuthMessage>>("IronBusinessServicePayload::auth_IronAuthMessage", pos),
          IronBusinessServicePayload::ddz_IronDdzMessage => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ddz::IronDdzMessage>>("IronBusinessServicePayload::ddz_IronDdzMessage", pos),
          IronBusinessServicePayload::pdk_IronPdkMessage => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<pdk::IronPdkMessage>>("IronBusinessServicePayload::pdk_IronPdkMessage", pos),
          _ => Ok(()),
        }
     })?
     .finish();
        Ok(())
    }
}
pub struct IronBusinessBodyArgs {
    pub payload_type: IronBusinessServicePayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for IronBusinessBodyArgs {
    #[inline]
    fn default() -> Self {
        IronBusinessBodyArgs {
            payload_type: IronBusinessServicePayload::NONE,
            payload: None,
        }
    }
}

pub struct IronBusinessBodyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronBusinessBodyBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_payload_type(&mut self, payload_type: IronBusinessServicePayload) {
        self.fbb_.push_slot::<IronBusinessServicePayload>(
            IronBusinessBody::VT_PAYLOAD_TYPE,
            payload_type,
            IronBusinessServicePayload::NONE,
        );
    }
    #[inline]
    pub fn add_payload(
        &mut self,
        payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronBusinessBody::VT_PAYLOAD, payload);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronBusinessBodyBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronBusinessBodyBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronBusinessBody<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronBusinessBody<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronBusinessBody");
        ds.field("payload_type", &self.payload_type());
        match self.payload_type() {
            IronBusinessServicePayload::auth_IronAuthMessage => {
                if let Some(x) = self.payload_as_auth_iron_auth_message() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronBusinessServicePayload::ddz_IronDdzMessage => {
                if let Some(x) = self.payload_as_ddz_iron_ddz_message() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronBusinessServicePayload::pdk_IronPdkMessage => {
                if let Some(x) = self.payload_as_pdk_iron_pdk_message() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            _ => {
                let x: Option<()> = None;
                ds.field("payload", &x)
            }
        };
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `IronBusinessBody`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_business_body_unchecked`.
pub fn root_as_iron_business_body(
    buf: &[u8],
) -> Result<IronBusinessBody<'_>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::root::<IronBusinessBody>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `IronBusinessBody` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_iron_business_body_unchecked`.
pub fn size_prefixed_root_as_iron_business_body(
    buf: &[u8],
) -> Result<IronBusinessBody<'_>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::size_prefixed_root::<IronBusinessBody>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `IronBusinessBody` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_business_body_unchecked`.
pub fn root_as_iron_business_body_with_opts<'b, 'o>(
    opts: &'o ::flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<IronBusinessBody<'b>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::root_with_opts::<IronBusinessBody<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `IronBusinessBody` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_business_body_unchecked`.
pub fn size_prefixed_root_as_iron_business_body_with_opts<'b, 'o>(
    opts: &'o ::flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<IronBusinessBody<'b>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::size_prefixed_root_with_opts::<IronBusinessBody<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a IronBusinessBody and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `IronBusinessBody`.
pub unsafe fn root_as_iron_business_body_unchecked(buf: &[u8]) -> IronBusinessBody<'_> {
    unsafe { ::flatbuffers::root_unchecked::<IronBusinessBody>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed IronBusinessBody and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `IronBusinessBody`.
pub unsafe fn size_prefixed_root_as_iron_business_body_unchecked(
    buf: &[u8],
) -> IronBusinessBody<'_> {
    unsafe { ::flatbuffers::size_prefixed_root_unchecked::<IronBusinessBody>(buf) }
}
#[inline]
pub fn finish_iron_business_body_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<IronBusinessBody<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_iron_business_body_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<IronBusinessBody<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
