// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronClusterNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronClusterNode<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronClusterNode<'a> {
    type Inner = IronClusterNode<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronClusterNode<'a> {
    pub const VT_NODE_ID: ::flatbuffers::VOffsetT = 4;
    pub const VT_ROLE: ::flatbuffers::VOffsetT = 6;
    pub const VT_STATE: ::flatbuffers::VOffsetT = 8;
    pub const VT_SERVICES: ::flatbuffers::VOffsetT = 10;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronClusterNode { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronClusterNodeArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronClusterNode<'bldr>> {
        let mut builder = IronClusterNodeBuilder::new(_fbb);
        if let Some(x) = args.services {
            builder.add_services(x);
        }
        if let Some(x) = args.node_id {
            builder.add_node_id(x);
        }
        builder.add_state(args.state);
        builder.add_role(args.role);
        builder.finish()
    }

    #[inline]
    pub fn node_id(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronClusterNode::VT_NODE_ID, None)
        }
    }
    #[inline]
    pub fn role(&self) -> IronClusterNodeRole {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronClusterNodeRole>(
                    IronClusterNode::VT_ROLE,
                    Some(IronClusterNodeRole::Gateway),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn state(&self) -> IronClusterState {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronClusterState>(IronClusterNode::VT_STATE, Some(IronClusterState::Unknown))
                .unwrap()
        }
    }
    #[inline]
    pub fn services(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterService<'a>>>>
    {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterService>>,
            >>(IronClusterNode::VT_SERVICES, None)
        }
    }
}

impl ::flatbuffers::Verifiable for IronClusterNode<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                "node_id",
                Self::VT_NODE_ID,
                false,
            )?
            .visit_field::<IronClusterNodeRole>("role", Self::VT_ROLE, false)?
            .visit_field::<IronClusterState>("state", Self::VT_STATE, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<IronClusterService>>,
            >>("services", Self::VT_SERVICES, false)?
            .finish();
        Ok(())
    }
}
pub struct IronClusterNodeArgs<'a> {
    pub node_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub role: IronClusterNodeRole,
    pub state: IronClusterState,
    pub services: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterService<'a>>>,
        >,
    >,
}
impl<'a> Default for IronClusterNodeArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronClusterNodeArgs {
            node_id: None,
            role: IronClusterNodeRole::Gateway,
            state: IronClusterState::Unknown,
            services: None,
        }
    }
}

pub struct IronClusterNodeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterNodeBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_node_id(&mut self, node_id: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronClusterNode::VT_NODE_ID, node_id);
    }
    #[inline]
    pub fn add_role(&mut self, role: IronClusterNodeRole) {
        self.fbb_.push_slot::<IronClusterNodeRole>(
            IronClusterNode::VT_ROLE,
            role,
            IronClusterNodeRole::Gateway,
        );
    }
    #[inline]
    pub fn add_state(&mut self, state: IronClusterState) {
        self.fbb_.push_slot::<IronClusterState>(
            IronClusterNode::VT_STATE,
            state,
            IronClusterState::Unknown,
        );
    }
    #[inline]
    pub fn add_services(
        &mut self,
        services: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<IronClusterService<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            IronClusterNode::VT_SERVICES,
            services,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronClusterNodeBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronClusterNodeBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterNode<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronClusterNode<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronClusterNode");
        ds.field("node_id", &self.node_id());
        ds.field("role", &self.role());
        ds.field("state", &self.state());
        ds.field("services", &self.services());
        ds.finish()
    }
}
