// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronClusterServiceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronClusterService<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronClusterService<'a> {
    type Inner = IronClusterService<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronClusterService<'a> {
    pub const VT_SERVICE_NAME: ::flatbuffers::VOffsetT = 4;
    pub const VT_STATE: ::flatbuffers::VOffsetT = 6;
    pub const VT_ENDPOINTS: ::flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronClusterService { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronClusterServiceArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronClusterService<'bldr>> {
        let mut builder = IronClusterServiceBuilder::new(_fbb);
        if let Some(x) = args.endpoints {
            builder.add_endpoints(x);
        }
        if let Some(x) = args.service_name {
            builder.add_service_name(x);
        }
        builder.add_state(args.state);
        builder.finish()
    }

    #[inline]
    pub fn service_name(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                IronClusterService::VT_SERVICE_NAME,
                None,
            )
        }
    }
    #[inline]
    pub fn state(&self) -> IronClusterState {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronClusterState>(
                    IronClusterService::VT_STATE,
                    Some(IronClusterState::Unknown),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn endpoints(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'a>>>>
    {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterEndpoint>>,
            >>(IronClusterService::VT_ENDPOINTS, None)
        }
    }
}

impl ::flatbuffers::Verifiable for IronClusterService<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                "service_name",
                Self::VT_SERVICE_NAME,
                false,
            )?
            .visit_field::<IronClusterState>("state", Self::VT_STATE, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<IronClusterEndpoint>>,
            >>("endpoints", Self::VT_ENDPOINTS, false)?
            .finish();
        Ok(())
    }
}
pub struct IronClusterServiceArgs<'a> {
    pub service_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub state: IronClusterState,
    pub endpoints: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'a>>>,
        >,
    >,
}
impl<'a> Default for IronClusterServiceArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronClusterServiceArgs {
            service_name: None,
            state: IronClusterState::Unknown,
            endpoints: None,
        }
    }
}

pub struct IronClusterServiceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterServiceBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_service_name(&mut self, service_name: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            IronClusterService::VT_SERVICE_NAME,
            service_name,
        );
    }
    #[inline]
    pub fn add_state(&mut self, state: IronClusterState) {
        self.fbb_.push_slot::<IronClusterState>(
            IronClusterService::VT_STATE,
            state,
            IronClusterState::Unknown,
        );
    }
    #[inline]
    pub fn add_endpoints(
        &mut self,
        endpoints: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<IronClusterEndpoint<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            IronClusterService::VT_ENDPOINTS,
            endpoints,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronClusterServiceBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronClusterServiceBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterService<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronClusterService<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronClusterService");
        ds.field("service_name", &self.service_name());
        ds.field("state", &self.state());
        ds.field("endpoints", &self.endpoints());
        ds.finish()
    }
}
