// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronClusterEndpointOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronClusterEndpoint<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronClusterEndpoint<'a> {
    type Inner = IronClusterEndpoint<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronClusterEndpoint<'a> {
    pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
    pub const VT_PROTOCOL: ::flatbuffers::VOffsetT = 6;
    pub const VT_HOST: ::flatbuffers::VOffsetT = 8;
    pub const VT_PORT: ::flatbuffers::VOffsetT = 10;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronClusterEndpoint { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronClusterEndpointArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronClusterEndpoint<'bldr>> {
        let mut builder = IronClusterEndpointBuilder::new(_fbb);
        if let Some(x) = args.host {
            builder.add_host(x);
        }
        if let Some(x) = args.name {
            builder.add_name(x);
        }
        builder.add_port(args.port);
        builder.add_protocol(args.protocol);
        builder.finish()
    }

    #[inline]
    pub fn name(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronClusterEndpoint::VT_NAME, None)
        }
    }
    #[inline]
    pub fn protocol(&self) -> IronClusterEndpointProtocol {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronClusterEndpointProtocol>(
                    IronClusterEndpoint::VT_PROTOCOL,
                    Some(IronClusterEndpointProtocol::Tcp),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn host(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronClusterEndpoint::VT_HOST, None)
        }
    }
    #[inline]
    pub fn port(&self) -> u16 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u16>(IronClusterEndpoint::VT_PORT, Some(0))
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IronClusterEndpoint<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
            .visit_field::<IronClusterEndpointProtocol>("protocol", Self::VT_PROTOCOL, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("host", Self::VT_HOST, false)?
            .visit_field::<u16>("port", Self::VT_PORT, false)?
            .finish();
        Ok(())
    }
}
pub struct IronClusterEndpointArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub protocol: IronClusterEndpointProtocol,
    pub host: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub port: u16,
}
impl<'a> Default for IronClusterEndpointArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronClusterEndpointArgs {
            name: None,
            protocol: IronClusterEndpointProtocol::Tcp,
            host: None,
            port: 0,
        }
    }
}

pub struct IronClusterEndpointBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterEndpointBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronClusterEndpoint::VT_NAME, name);
    }
    #[inline]
    pub fn add_protocol(&mut self, protocol: IronClusterEndpointProtocol) {
        self.fbb_.push_slot::<IronClusterEndpointProtocol>(
            IronClusterEndpoint::VT_PROTOCOL,
            protocol,
            IronClusterEndpointProtocol::Tcp,
        );
    }
    #[inline]
    pub fn add_host(&mut self, host: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronClusterEndpoint::VT_HOST, host);
    }
    #[inline]
    pub fn add_port(&mut self, port: u16) {
        self.fbb_
            .push_slot::<u16>(IronClusterEndpoint::VT_PORT, port, 0);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronClusterEndpointBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronClusterEndpointBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterEndpoint<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronClusterEndpoint<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronClusterEndpoint");
        ds.field("name", &self.name());
        ds.field("protocol", &self.protocol());
        ds.field("host", &self.host());
        ds.field("port", &self.port());
        ds.finish()
    }
}
