// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronClusterSnapOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronClusterSnap<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronClusterSnap<'a> {
    type Inner = IronClusterSnap<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronClusterSnap<'a> {
    pub const VT_CLUSTER_ID: ::flatbuffers::VOffsetT = 4;
    pub const VT_METADATA_VERSION: ::flatbuffers::VOffsetT = 6;
    pub const VT_NODES: ::flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronClusterSnap { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronClusterSnapArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronClusterSnap<'bldr>> {
        let mut builder = IronClusterSnapBuilder::new(_fbb);
        builder.add_metadata_version(args.metadata_version);
        if let Some(x) = args.nodes {
            builder.add_nodes(x);
        }
        if let Some(x) = args.cluster_id {
            builder.add_cluster_id(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn cluster_id(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<&str>>(IronClusterSnap::VT_CLUSTER_ID, None)
        }
    }
    #[inline]
    pub fn metadata_version(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronClusterSnap::VT_METADATA_VERSION, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn nodes(
        &self,
    ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterNode<'a>>>>
    {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterNode>>,
            >>(IronClusterSnap::VT_NODES, None)
        }
    }
}

impl ::flatbuffers::Verifiable for IronClusterSnap<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                "cluster_id",
                Self::VT_CLUSTER_ID,
                false,
            )?
            .visit_field::<u64>("metadata_version", Self::VT_METADATA_VERSION, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<
                ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<IronClusterNode>>,
            >>("nodes", Self::VT_NODES, false)?
            .finish();
        Ok(())
    }
}
pub struct IronClusterSnapArgs<'a> {
    pub cluster_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub metadata_version: u64,
    pub nodes: Option<
        ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IronClusterNode<'a>>>,
        >,
    >,
}
impl<'a> Default for IronClusterSnapArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronClusterSnapArgs {
            cluster_id: None,
            metadata_version: 0,
            nodes: None,
        }
    }
}

pub struct IronClusterSnapBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronClusterSnapBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_cluster_id(&mut self, cluster_id: ::flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
            IronClusterSnap::VT_CLUSTER_ID,
            cluster_id,
        );
    }
    #[inline]
    pub fn add_metadata_version(&mut self, metadata_version: u64) {
        self.fbb_
            .push_slot::<u64>(IronClusterSnap::VT_METADATA_VERSION, metadata_version, 0);
    }
    #[inline]
    pub fn add_nodes(
        &mut self,
        nodes: ::flatbuffers::WIPOffset<
            ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<IronClusterNode<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronClusterSnap::VT_NODES, nodes);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronClusterSnapBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronClusterSnapBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronClusterSnap<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronClusterSnap<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronClusterSnap");
        ds.field("cluster_id", &self.cluster_id());
        ds.field("metadata_version", &self.metadata_version());
        ds.field("nodes", &self.nodes());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `IronClusterSnap`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_cluster_snap_unchecked`.
pub fn root_as_iron_cluster_snap(
    buf: &[u8],
) -> Result<IronClusterSnap<'_>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::root::<IronClusterSnap>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `IronClusterSnap` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_iron_cluster_snap_unchecked`.
pub fn size_prefixed_root_as_iron_cluster_snap(
    buf: &[u8],
) -> Result<IronClusterSnap<'_>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::size_prefixed_root::<IronClusterSnap>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `IronClusterSnap` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_cluster_snap_unchecked`.
pub fn root_as_iron_cluster_snap_with_opts<'b, 'o>(
    opts: &'o ::flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<IronClusterSnap<'b>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::root_with_opts::<IronClusterSnap<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `IronClusterSnap` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_iron_cluster_snap_unchecked`.
pub fn size_prefixed_root_as_iron_cluster_snap_with_opts<'b, 'o>(
    opts: &'o ::flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<IronClusterSnap<'b>, ::flatbuffers::InvalidFlatbuffer> {
    ::flatbuffers::size_prefixed_root_with_opts::<IronClusterSnap<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a IronClusterSnap and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `IronClusterSnap`.
pub unsafe fn root_as_iron_cluster_snap_unchecked(buf: &[u8]) -> IronClusterSnap<'_> {
    unsafe { ::flatbuffers::root_unchecked::<IronClusterSnap>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed IronClusterSnap and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `IronClusterSnap`.
pub unsafe fn size_prefixed_root_as_iron_cluster_snap_unchecked(buf: &[u8]) -> IronClusterSnap<'_> {
    unsafe { ::flatbuffers::size_prefixed_root_unchecked::<IronClusterSnap>(buf) }
}
#[inline]
pub fn finish_iron_cluster_snap_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<IronClusterSnap<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_iron_cluster_snap_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<IronClusterSnap<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
