// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronPdkMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronPdkMessage<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronPdkMessage<'a> {
    type Inner = IronPdkMessage<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronPdkMessage<'a> {
    pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
    pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronPdkMessage { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronPdkMessageArgs,
    ) -> ::flatbuffers::WIPOffset<IronPdkMessage<'bldr>> {
        let mut builder = IronPdkMessageBuilder::new(_fbb);
        if let Some(x) = args.payload {
            builder.add_payload(x);
        }
        builder.add_payload_type(args.payload_type);
        builder.finish()
    }

    #[inline]
    pub fn payload_type(&self) -> IronPdkPayload {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronPdkPayload>(IronPdkMessage::VT_PAYLOAD_TYPE, Some(IronPdkPayload::NONE))
                .unwrap()
        }
    }
    #[inline]
    pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    IronPdkMessage::VT_PAYLOAD,
                    None,
                )
        }
    }
    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_pdk_start_req(&self) -> Option<IronPdkStartReq<'a>> {
        if self.payload_type() == IronPdkPayload::IronPdkStartReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronPdkStartReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_pdk_start_resp(&self) -> Option<IronPdkStartResp<'a>> {
        if self.payload_type() == IronPdkPayload::IronPdkStartResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronPdkStartResp::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_pdk_play_card_req(&self) -> Option<IronPdkPlayCardReq<'a>> {
        if self.payload_type() == IronPdkPayload::IronPdkPlayCardReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronPdkPlayCardReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_pdk_play_card_resp(&self) -> Option<IronPdkPlayCardResp<'a>> {
        if self.payload_type() == IronPdkPayload::IronPdkPlayCardResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronPdkPlayCardResp::init_from_table(t) }
            })
        } else {
            None
        }
    }
}

impl ::flatbuffers::Verifiable for IronPdkMessage<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
     .visit_union::<IronPdkPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          IronPdkPayload::IronPdkStartReq => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronPdkStartReq>>("IronPdkPayload::IronPdkStartReq", pos),
          IronPdkPayload::IronPdkStartResp => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronPdkStartResp>>("IronPdkPayload::IronPdkStartResp", pos),
          IronPdkPayload::IronPdkPlayCardReq => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronPdkPlayCardReq>>("IronPdkPayload::IronPdkPlayCardReq", pos),
          IronPdkPayload::IronPdkPlayCardResp => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<IronPdkPlayCardResp>>("IronPdkPayload::IronPdkPlayCardResp", pos),
          _ => Ok(()),
        }
     })?
     .finish();
        Ok(())
    }
}
pub struct IronPdkMessageArgs {
    pub payload_type: IronPdkPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for IronPdkMessageArgs {
    #[inline]
    fn default() -> Self {
        IronPdkMessageArgs {
            payload_type: IronPdkPayload::NONE,
            payload: None,
        }
    }
}

pub struct IronPdkMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronPdkMessageBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_payload_type(&mut self, payload_type: IronPdkPayload) {
        self.fbb_.push_slot::<IronPdkPayload>(
            IronPdkMessage::VT_PAYLOAD_TYPE,
            payload_type,
            IronPdkPayload::NONE,
        );
    }
    #[inline]
    pub fn add_payload(
        &mut self,
        payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronPdkMessage::VT_PAYLOAD, payload);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronPdkMessageBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronPdkMessageBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronPdkMessage<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronPdkMessage<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronPdkMessage");
        ds.field("payload_type", &self.payload_type());
        match self.payload_type() {
            IronPdkPayload::IronPdkStartReq => {
                if let Some(x) = self.payload_as_iron_pdk_start_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronPdkPayload::IronPdkStartResp => {
                if let Some(x) = self.payload_as_iron_pdk_start_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronPdkPayload::IronPdkPlayCardReq => {
                if let Some(x) = self.payload_as_iron_pdk_play_card_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronPdkPayload::IronPdkPlayCardResp => {
                if let Some(x) = self.payload_as_iron_pdk_play_card_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            _ => {
                let x: Option<()> = None;
                ds.field("payload", &x)
            }
        };
        ds.finish()
    }
}
