// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronPdkPlayCardReqOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronPdkPlayCardReq<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronPdkPlayCardReq<'a> {
    type Inner = IronPdkPlayCardReq<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronPdkPlayCardReq<'a> {
    pub const VT_ROOM_ID: ::flatbuffers::VOffsetT = 4;
    pub const VT_CARDS: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronPdkPlayCardReq { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronPdkPlayCardReqArgs<'args>,
    ) -> ::flatbuffers::WIPOffset<IronPdkPlayCardReq<'bldr>> {
        let mut builder = IronPdkPlayCardReqBuilder::new(_fbb);
        builder.add_room_id(args.room_id);
        if let Some(x) = args.cards {
            builder.add_cards(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn room_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronPdkPlayCardReq::VT_ROOM_ID, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn cards(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                    IronPdkPlayCardReq::VT_CARDS,
                    None,
                )
        }
    }
}

impl ::flatbuffers::Verifiable for IronPdkPlayCardReq<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<u64>("room_id", Self::VT_ROOM_ID, false)?
            .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                "cards",
                Self::VT_CARDS,
                false,
            )?
            .finish();
        Ok(())
    }
}
pub struct IronPdkPlayCardReqArgs<'a> {
    pub room_id: u64,
    pub cards: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for IronPdkPlayCardReqArgs<'a> {
    #[inline]
    fn default() -> Self {
        IronPdkPlayCardReqArgs {
            room_id: 0,
            cards: None,
        }
    }
}

pub struct IronPdkPlayCardReqBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronPdkPlayCardReqBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_room_id(&mut self, room_id: u64) {
        self.fbb_
            .push_slot::<u64>(IronPdkPlayCardReq::VT_ROOM_ID, room_id, 0);
    }
    #[inline]
    pub fn add_cards(&mut self, cards: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronPdkPlayCardReq::VT_CARDS, cards);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronPdkPlayCardReqBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronPdkPlayCardReqBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronPdkPlayCardReq<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronPdkPlayCardReq<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronPdkPlayCardReq");
        ds.field("room_id", &self.room_id());
        ds.field("cards", &self.cards());
        ds.finish()
    }
}
