// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronPdkPlayCardRespOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronPdkPlayCardResp<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronPdkPlayCardResp<'a> {
    type Inner = IronPdkPlayCardResp<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronPdkPlayCardResp<'a> {
    pub const VT_CODE: ::flatbuffers::VOffsetT = 4;
    pub const VT_ROOM_ID: ::flatbuffers::VOffsetT = 6;
    pub const VT_NEXT_PLAYER_USER_ID: ::flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronPdkPlayCardResp { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronPdkPlayCardRespArgs,
    ) -> ::flatbuffers::WIPOffset<IronPdkPlayCardResp<'bldr>> {
        let mut builder = IronPdkPlayCardRespBuilder::new(_fbb);
        builder.add_next_player_user_id(args.next_player_user_id);
        builder.add_room_id(args.room_id);
        builder.add_code(args.code);
        builder.finish()
    }

    #[inline]
    pub fn code(&self) -> IronPdkErrorCode {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronPdkErrorCode>(IronPdkPlayCardResp::VT_CODE, Some(IronPdkErrorCode::Ok))
                .unwrap()
        }
    }
    #[inline]
    pub fn room_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronPdkPlayCardResp::VT_ROOM_ID, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn next_player_user_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronPdkPlayCardResp::VT_NEXT_PLAYER_USER_ID, Some(0))
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IronPdkPlayCardResp<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<IronPdkErrorCode>("code", Self::VT_CODE, false)?
            .visit_field::<u64>("room_id", Self::VT_ROOM_ID, false)?
            .visit_field::<u64>("next_player_user_id", Self::VT_NEXT_PLAYER_USER_ID, false)?
            .finish();
        Ok(())
    }
}
pub struct IronPdkPlayCardRespArgs {
    pub code: IronPdkErrorCode,
    pub room_id: u64,
    pub next_player_user_id: u64,
}
impl<'a> Default for IronPdkPlayCardRespArgs {
    #[inline]
    fn default() -> Self {
        IronPdkPlayCardRespArgs {
            code: IronPdkErrorCode::Ok,
            room_id: 0,
            next_player_user_id: 0,
        }
    }
}

pub struct IronPdkPlayCardRespBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronPdkPlayCardRespBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_code(&mut self, code: IronPdkErrorCode) {
        self.fbb_.push_slot::<IronPdkErrorCode>(
            IronPdkPlayCardResp::VT_CODE,
            code,
            IronPdkErrorCode::Ok,
        );
    }
    #[inline]
    pub fn add_room_id(&mut self, room_id: u64) {
        self.fbb_
            .push_slot::<u64>(IronPdkPlayCardResp::VT_ROOM_ID, room_id, 0);
    }
    #[inline]
    pub fn add_next_player_user_id(&mut self, next_player_user_id: u64) {
        self.fbb_.push_slot::<u64>(
            IronPdkPlayCardResp::VT_NEXT_PLAYER_USER_ID,
            next_player_user_id,
            0,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronPdkPlayCardRespBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronPdkPlayCardRespBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronPdkPlayCardResp<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronPdkPlayCardResp<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronPdkPlayCardResp");
        ds.field("code", &self.code());
        ds.field("room_id", &self.room_id());
        ds.field("next_player_user_id", &self.next_player_user_id());
        ds.finish()
    }
}
