# 集群种子节点配置。
[[peers]]
raft_node_id = 1
node_id = "iron-gateway-1"
http_url = "http://127.0.0.1:7101"

[[peers]]
raft_node_id = 2
node_id = "iron-service-auth-1"
http_url = "http://127.0.0.1:7102"

[[peers]]
raft_node_id = 3
node_id = "iron-service-ddz-1"
http_url = "http://127.0.0.1:7103"

[[peers]]
raft_node_id = 4
node_id = "iron-service-pdk-1"
http_url = "http://127.0.0.1:7104"
