// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronDdzGrabRespOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronDdzGrabResp<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronDdzGrabResp<'a> {
    type Inner = IronDdzGrabResp<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronDdzGrabResp<'a> {
    pub const VT_CODE: ::flatbuffers::VOffsetT = 4;
    pub const VT_ROOM_ID: ::flatbuffers::VOffsetT = 6;
    pub const VT_LANDLORD_USER_ID: ::flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronDdzGrabResp { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronDdzGrabRespArgs,
    ) -> ::flatbuffers::WIPOffset<IronDdzGrabResp<'bldr>> {
        let mut builder = IronDdzGrabRespBuilder::new(_fbb);
        builder.add_landlord_user_id(args.landlord_user_id);
        builder.add_room_id(args.room_id);
        builder.add_code(args.code);
        builder.finish()
    }

    #[inline]
    pub fn code(&self) -> IronDdzErrorCode {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronDdzErrorCode>(IronDdzGrabResp::VT_CODE, Some(IronDdzErrorCode::Ok))
                .unwrap()
        }
    }
    #[inline]
    pub fn room_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronDdzGrabResp::VT_ROOM_ID, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn landlord_user_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronDdzGrabResp::VT_LANDLORD_USER_ID, Some(0))
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IronDdzGrabResp<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<IronDdzErrorCode>("code", Self::VT_CODE, false)?
            .visit_field::<u64>("room_id", Self::VT_ROOM_ID, false)?
            .visit_field::<u64>("landlord_user_id", Self::VT_LANDLORD_USER_ID, false)?
            .finish();
        Ok(())
    }
}
pub struct IronDdzGrabRespArgs {
    pub code: IronDdzErrorCode,
    pub room_id: u64,
    pub landlord_user_id: u64,
}
impl<'a> Default for IronDdzGrabRespArgs {
    #[inline]
    fn default() -> Self {
        IronDdzGrabRespArgs {
            code: IronDdzErrorCode::Ok,
            room_id: 0,
            landlord_user_id: 0,
        }
    }
}

pub struct IronDdzGrabRespBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronDdzGrabRespBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_code(&mut self, code: IronDdzErrorCode) {
        self.fbb_.push_slot::<IronDdzErrorCode>(
            IronDdzGrabResp::VT_CODE,
            code,
            IronDdzErrorCode::Ok,
        );
    }
    #[inline]
    pub fn add_room_id(&mut self, room_id: u64) {
        self.fbb_
            .push_slot::<u64>(IronDdzGrabResp::VT_ROOM_ID, room_id, 0);
    }
    #[inline]
    pub fn add_landlord_user_id(&mut self, landlord_user_id: u64) {
        self.fbb_
            .push_slot::<u64>(IronDdzGrabResp::VT_LANDLORD_USER_ID, landlord_user_id, 0);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronDdzGrabRespBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronDdzGrabRespBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronDdzGrabResp<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronDdzGrabResp<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronDdzGrabResp");
        ds.field("code", &self.code());
        ds.field("room_id", &self.room_id());
        ds.field("landlord_user_id", &self.landlord_user_id());
        ds.finish()
    }
}
