// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronDdzStartReqOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronDdzStartReq<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronDdzStartReq<'a> {
    type Inner = IronDdzStartReq<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronDdzStartReq<'a> {
    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronDdzStartReq { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        _args: &'args IronDdzStartReqArgs,
    ) -> ::flatbuffers::WIPOffset<IronDdzStartReq<'bldr>> {
        let mut builder = IronDdzStartReqBuilder::new(_fbb);
        builder.finish()
    }
}

impl ::flatbuffers::Verifiable for IronDdzStartReq<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?.finish();
        Ok(())
    }
}
pub struct IronDdzStartReqArgs {}
impl<'a> Default for IronDdzStartReqArgs {
    #[inline]
    fn default() -> Self {
        IronDdzStartReqArgs {}
    }
}

pub struct IronDdzStartReqBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronDdzStartReqBuilder<'a, 'b, A> {
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronDdzStartReqBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronDdzStartReqBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronDdzStartReq<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronDdzStartReq<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronDdzStartReq");
        ds.finish()
    }
}
