// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronDdzMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronDdzMessage<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronDdzMessage<'a> {
    type Inner = IronDdzMessage<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronDdzMessage<'a> {
    pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 4;
    pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronDdzMessage { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronDdzMessageArgs,
    ) -> ::flatbuffers::WIPOffset<IronDdzMessage<'bldr>> {
        let mut builder = IronDdzMessageBuilder::new(_fbb);
        if let Some(x) = args.payload {
            builder.add_payload(x);
        }
        builder.add_payload_type(args.payload_type);
        builder.finish()
    }

    #[inline]
    pub fn payload_type(&self) -> IronDdzPayload {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<IronDdzPayload>(IronDdzMessage::VT_PAYLOAD_TYPE, Some(IronDdzPayload::NONE))
                .unwrap()
        }
    }
    #[inline]
    pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    IronDdzMessage::VT_PAYLOAD,
                    None,
                )
        }
    }
    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_ddz_start_req(&self) -> Option<IronDdzStartReq<'a>> {
        if self.payload_type() == IronDdzPayload::IronDdzStartReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronDdzStartReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_ddz_start_resp(&self) -> Option<IronDdzStartResp<'a>> {
        if self.payload_type() == IronDdzPayload::IronDdzStartResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronDdzStartResp::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_ddz_grab_req(&self) -> Option<IronDdzGrabReq<'a>> {
        if self.payload_type() == IronDdzPayload::IronDdzGrabReq {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronDdzGrabReq::init_from_table(t) }
            })
        } else {
            None
        }
    }

    #[inline]
    #[allow(non_snake_case)]
    pub fn payload_as_iron_ddz_grab_resp(&self) -> Option<IronDdzGrabResp<'a>> {
        if self.payload_type() == IronDdzPayload::IronDdzGrabResp {
            self.payload().map(|t| {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                unsafe { IronDdzGrabResp::init_from_table(t) }
            })
        } else {
            None
        }
    }
}

impl ::flatbuffers::Verifiable for IronDdzMessage<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_union::<IronDdzPayload, _>(
                "payload_type",
                Self::VT_PAYLOAD_TYPE,
                "payload",
                Self::VT_PAYLOAD,
                false,
                |key, v, pos| match key {
                    IronDdzPayload::IronDdzStartReq => v
                        .verify_union_variant::<::flatbuffers::ForwardsUOffset<IronDdzStartReq>>(
                            "IronDdzPayload::IronDdzStartReq",
                            pos,
                        ),
                    IronDdzPayload::IronDdzStartResp => v
                        .verify_union_variant::<::flatbuffers::ForwardsUOffset<IronDdzStartResp>>(
                            "IronDdzPayload::IronDdzStartResp",
                            pos,
                        ),
                    IronDdzPayload::IronDdzGrabReq => v
                        .verify_union_variant::<::flatbuffers::ForwardsUOffset<IronDdzGrabReq>>(
                            "IronDdzPayload::IronDdzGrabReq",
                            pos,
                        ),
                    IronDdzPayload::IronDdzGrabResp => v
                        .verify_union_variant::<::flatbuffers::ForwardsUOffset<IronDdzGrabResp>>(
                            "IronDdzPayload::IronDdzGrabResp",
                            pos,
                        ),
                    _ => Ok(()),
                },
            )?
            .finish();
        Ok(())
    }
}
pub struct IronDdzMessageArgs {
    pub payload_type: IronDdzPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for IronDdzMessageArgs {
    #[inline]
    fn default() -> Self {
        IronDdzMessageArgs {
            payload_type: IronDdzPayload::NONE,
            payload: None,
        }
    }
}

pub struct IronDdzMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronDdzMessageBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_payload_type(&mut self, payload_type: IronDdzPayload) {
        self.fbb_.push_slot::<IronDdzPayload>(
            IronDdzMessage::VT_PAYLOAD_TYPE,
            payload_type,
            IronDdzPayload::NONE,
        );
    }
    #[inline]
    pub fn add_payload(
        &mut self,
        payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
    ) {
        self.fbb_
            .push_slot_always::<::flatbuffers::WIPOffset<_>>(IronDdzMessage::VT_PAYLOAD, payload);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronDdzMessageBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronDdzMessageBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronDdzMessage<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronDdzMessage<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronDdzMessage");
        ds.field("payload_type", &self.payload_type());
        match self.payload_type() {
            IronDdzPayload::IronDdzStartReq => {
                if let Some(x) = self.payload_as_iron_ddz_start_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronDdzPayload::IronDdzStartResp => {
                if let Some(x) = self.payload_as_iron_ddz_start_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronDdzPayload::IronDdzGrabReq => {
                if let Some(x) = self.payload_as_iron_ddz_grab_req() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            IronDdzPayload::IronDdzGrabResp => {
                if let Some(x) = self.payload_as_iron_ddz_grab_resp() {
                    ds.field("payload", &x)
                } else {
                    ds.field(
                        "payload",
                        &"InvalidFlatbuffer: Union discriminant does not match value.",
                    )
                }
            }
            _ => {
                let x: Option<()> = None;
                ds.field("payload", &x)
            }
        };
        ds.finish()
    }
}
