// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_IRON_DDZ_PAYLOAD: u8 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_IRON_DDZ_PAYLOAD: u8 = 4;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_IRON_DDZ_PAYLOAD: [IronDdzPayload; 5] = [
    IronDdzPayload::NONE,
    IronDdzPayload::IronDdzStartReq,
    IronDdzPayload::IronDdzStartResp,
    IronDdzPayload::IronDdzGrabReq,
    IronDdzPayload::IronDdzGrabResp,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IronDdzPayload(pub u8);
#[allow(non_upper_case_globals)]
impl IronDdzPayload {
    pub const NONE: Self = Self(0);
    pub const IronDdzStartReq: Self = Self(1);
    pub const IronDdzStartResp: Self = Self(2);
    pub const IronDdzGrabReq: Self = Self(3);
    pub const IronDdzGrabResp: Self = Self(4);

    pub const ENUM_MIN: u8 = 0;
    pub const ENUM_MAX: u8 = 4;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::NONE,
        Self::IronDdzStartReq,
        Self::IronDdzStartResp,
        Self::IronDdzGrabReq,
        Self::IronDdzGrabResp,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::NONE => Some("NONE"),
            Self::IronDdzStartReq => Some("IronDdzStartReq"),
            Self::IronDdzStartResp => Some("IronDdzStartResp"),
            Self::IronDdzGrabReq => Some("IronDdzGrabReq"),
            Self::IronDdzGrabResp => Some("IronDdzGrabResp"),
            _ => None,
        }
    }
}
impl ::core::fmt::Debug for IronDdzPayload {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> ::flatbuffers::Follow<'a> for IronDdzPayload {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
        Self(b)
    }
}

impl ::flatbuffers::Push for IronDdzPayload {
    type Output = IronDdzPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for IronDdzPayload {
    type Scalar = u8;
    #[inline]
    fn to_little_endian(self) -> u8 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: u8) -> Self {
        let b = u8::from_le(v);
        Self(b)
    }
}

impl<'a> ::flatbuffers::Verifiable for IronDdzPayload {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        u8::run_verifier(v, pos)
    }
}

impl ::flatbuffers::SimpleToVerifyInSlice for IronDdzPayload {}
pub struct IronDdzPayloadUnionTableOffset {}
