// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum IronDdzGrabReqOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IronDdzGrabReq<'a> {
    pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IronDdzGrabReq<'a> {
    type Inner = IronDdzGrabReq<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
        }
    }
}

impl<'a> IronDdzGrabReq<'a> {
    pub const VT_ROOM_ID: ::flatbuffers::VOffsetT = 4;
    pub const VT_GRAB: ::flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
        IronDdzGrabReq { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<
        'bldr: 'args,
        'args: 'mut_bldr,
        'mut_bldr,
        A: ::flatbuffers::Allocator + 'bldr,
    >(
        _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args IronDdzGrabReqArgs,
    ) -> ::flatbuffers::WIPOffset<IronDdzGrabReq<'bldr>> {
        let mut builder = IronDdzGrabReqBuilder::new(_fbb);
        builder.add_room_id(args.room_id);
        builder.add_grab(args.grab);
        builder.finish()
    }

    #[inline]
    pub fn room_id(&self) -> u64 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u64>(IronDdzGrabReq::VT_ROOM_ID, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn grab(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(IronDdzGrabReq::VT_GRAB, Some(false))
                .unwrap()
        }
    }
}

impl ::flatbuffers::Verifiable for IronDdzGrabReq<'_> {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<u64>("room_id", Self::VT_ROOM_ID, false)?
            .visit_field::<bool>("grab", Self::VT_GRAB, false)?
            .finish();
        Ok(())
    }
}
pub struct IronDdzGrabReqArgs {
    pub room_id: u64,
    pub grab: bool,
}
impl<'a> Default for IronDdzGrabReqArgs {
    #[inline]
    fn default() -> Self {
        IronDdzGrabReqArgs {
            room_id: 0,
            grab: false,
        }
    }
}

pub struct IronDdzGrabReqBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
    fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IronDdzGrabReqBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_room_id(&mut self, room_id: u64) {
        self.fbb_
            .push_slot::<u64>(IronDdzGrabReq::VT_ROOM_ID, room_id, 0);
    }
    #[inline]
    pub fn add_grab(&mut self, grab: bool) {
        self.fbb_
            .push_slot::<bool>(IronDdzGrabReq::VT_GRAB, grab, false);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> IronDdzGrabReqBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        IronDdzGrabReqBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> ::flatbuffers::WIPOffset<IronDdzGrabReq<'a>> {
        let o = self.fbb_.end_table(self.start_);
        ::flatbuffers::WIPOffset::new(o.value())
    }
}

impl ::core::fmt::Debug for IronDdzGrabReq<'_> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        let mut ds = f.debug_struct("IronDdzGrabReq");
        ds.field("room_id", &self.room_id());
        ds.field("grab", &self.grab());
        ds.finish()
    }
}
