// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_IRON_DDZ_ERROR_CODE: i32 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_IRON_DDZ_ERROR_CODE: i32 = 3;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_IRON_DDZ_ERROR_CODE: [IronDdzErrorCode; 4] = [
    IronDdzErrorCode::Ok,
    IronDdzErrorCode::Failed,
    IronDdzErrorCode::InvalidParam,
    IronDdzErrorCode::Unauthorized,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct IronDdzErrorCode(pub i32);
#[allow(non_upper_case_globals)]
impl IronDdzErrorCode {
    pub const Ok: Self = Self(0);
    pub const Failed: Self = Self(1);
    pub const InvalidParam: Self = Self(2);
    pub const Unauthorized: Self = Self(3);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 3;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::Ok,
        Self::Failed,
        Self::InvalidParam,
        Self::Unauthorized,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::Ok => Some("Ok"),
            Self::Failed => Some("Failed"),
            Self::InvalidParam => Some("InvalidParam"),
            Self::Unauthorized => Some("Unauthorized"),
            _ => None,
        }
    }
}
impl ::core::fmt::Debug for IronDdzErrorCode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> ::flatbuffers::Follow<'a> for IronDdzErrorCode {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = unsafe { ::flatbuffers::read_scalar_at::<i32>(buf, loc) };
        Self(b)
    }
}

impl ::flatbuffers::Push for IronDdzErrorCode {
    type Output = IronDdzErrorCode;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i32>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for IronDdzErrorCode {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: i32) -> Self {
        let b = i32::from_le(v);
        Self(b)
    }
}

impl<'a> ::flatbuffers::Verifiable for IronDdzErrorCode {
    #[inline]
    fn run_verifier(
        v: &mut ::flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
        i32::run_verifier(v, pos)
    }
}

impl ::flatbuffers::SimpleToVerifyInSlice for IronDdzErrorCode {}
